server:
  port: 80

spring:
  profiles:
      active: dev
  resources:
    static-locations: classpath:/templates/  # 静态资源路径

  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名

  redis:
    database: 1
    port: 6379
    password: lixizheng
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.spark.laboratory.pojo

#showSql
logging:
  level:
    com:
      spark:
        laboratory:
          mapper : debug